global:
  scrape_interval: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
remote_write:
  - url:  "http://influxdb1:8086/api/v1/prom/write?db=ngcdi_metrics"
scrape_configs:
  - job_name: 'RUNNAME_ca1'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor1:8080']
  - job_name: 'RUNNAME'
    scrape_interval: 5s
    static_configs:
    - targets: ['seed1:9095','prov1:9095','c1:9095','c2:9095','c3:9095','c4:9095','c5:9095','c6:9095','c7:9095','c8:9095','c9:9095','c10:9095','c11:9095','c12:9095','c13:9095','c14:9095','c15:9095','c16:9095','c17:9095','c18:9095','c19:9095','c20:9095','c21:9095','c22:9095','c23:9095','c24:9095','c25:9095']
