# run_containers.py base.yaml full.overlay.yaml

constants:
  run_name: netm_on_conm_on_ring_ag_topo1_1

  influxdb_q: 0
  cadvisor_q: 0
  prometheus_q: 0
  mininet_q: 0
  awareness_q: 0

  agent_sm_q: 0
  agent_fp_q: 0
  agent_da_q: 0

  mininet_topo: custom_mesh

  network_discovery_time: 40 # in seconds

  # ==================
  # internal constants
  # ==================

  network_name: mas-network
  influxdb_name: ngcdi_metrics

  # needs to be lazy because we are using constants $base_dir and $run_name
  # see examples/8-lazy-constants.yaml
  ^sckl_core_log_dir: $base_dir++/runs/++$run_name++/
  ^sckl_data_dir: $base_dir++/sckl-data/condition

  mininet_controllers: awareness1
  mininet_hostname: mininet
  mininet_switch: ovs
  mininet_server_url: http://mininet:8081

  awareness_hostname_prefix: awareness
  awareness_server_url: http://awareness1:8080
  awareness_cross_domain_links: ""

  core_transport_topology: ""
  core_neighbours: ""
  da_launcher: "awareness,agtopo1"

  ^agent_common_config:
    image: ngcdi/sckl-demo:0.6
    command: ""
    # auto_remove: True
    mem_limit: 550m
    mem_reservation: 500m
    network: $network_name
    environment:
      CLUSTER_PORT: 1600
      SEED_PORT_1600_TCP_ADDR: seed1
      SEED_PORT_1600_TCP_PORT: 1600
      DATADIR: data/
      SDNC_SERVER: awareness
      SDNC_PORT: 8080
      NETW_SERVER: mininet
      NETW_PORT: 9081
      NETW_API_KEY: ""
      NETW_URLS:
      - api/get_intent
      - api/push_intent
      LEFT_NEIGHBOUR: "seed0"
      RIGHT_NEIGHBOUR: "seed1"
      NEIGHBOURS: $core_neighbours
      AWARENESS_SERVER_URL: $awareness_server_url
      UI_URL: ""
      MONITORING_URL: /stats/port/
      NODES: ++$agent_da_q
      KEY_SERVICES: $key_services
      AWARENESS_CROSS_DOMAIN_LINKS: $awareness_cross_domain_links
      TRANSPORT_TOPOLOGY: $core_transport_topology
      DA_LAUNCHER: $da_launcher
    volumes:
      $^sckl_data_dir:
        bind: /data
        mode: ro

  ^agent_common_rules:
    - value: $^agent_common_config
    - target: [name, hostname, environment->CLUSTER_IP]
      value: $name_prefix++$id
      local_constants:
        - name: id
          type: auto_increment
          start: 1
    - target: environment->LAUNCHER
      value: $launcher
    - target: environment->DEV_ID
      value: ++$id
      local_constants:
        - name: id
          type: auto_increment
          start: 1
    - target: volumes->$^sckl_core_log_dir++$name++.log
      value:
        bind: /opt/docker/logs/app.log
        mode: rw
      local_constants:
        - name: name
          type: from_property
          source: name

  ^agent_common_hooks:
    preup:
      commands:
      - "> $LOG_FILE"
      - chmod a+w $LOG_FILE
      environment:
      - name: LOG_FILE
        value: $^sckl_core_log_dir++$name++.log
      local_constants:
        - name: name
          type: from_property
          source: name
    preup-global:
      commands:
      - mkdir -p $LOG_DIR
      environment:
      - name: LOG_DIR
        value: $^sckl_core_log_dir

groups:
  influxdb:
    containers: $influxdb_q

    rules:
      # if you are wondering why there is no "target" specified, see examples/7-tricks.yaml
      - value:
          image: influxdb:1.7
          command: ""
          name: influxdb1
          mem_limit: 500m
          mem_reservation: 450m
          network: $network_name
          volumes:
            influxdb1_datest1:
              bind: /var/lib/influxdb
              mode: rw
          ports:
            8086: 18086
          environment:
            INFLUXDB_DB: $influxdb_name

  cadvisor:
    containers: $cadvisor_q

    rules:
      - value:
          image: google/cadvisor:latest
          command:
          name: cadvisor1
          privileged: True
          mem_limit: 350m
          mem_reservation: 300m
          network: $network_name
          ports:
            8080: 9080
          volumes:
            /:
              bind: /rootfs
              mode: ro
            /var/run:
              bind: /var/run
              mode: rw
            /sys:
              bind: /sys
              mode: ro
            /snap/docker:
              bind: /var/lib/docker
              mode: ro
          environment:
            storage_driver: influxdb
            storage_driver_db: $influxdb_name
            storage_driver_host: influxdb1:8086

  prometheus:
    containers: $prometheus_q
    hooks:
      preup-global:
        commands:
          - sed "s/RUNNAME/$RUNNAME/" $CONFIG_FILE_TEMPLATE > $CONFIG_FILE
        environment:
          - name: RUNNAME
            value: $run_name
          - name: CONFIG_FILE_TEMPLATE
            value: $base_dir++/configs/prometheus/config.template.yml
          - name: CONFIG_FILE
            value: $base_dir++/configs/prometheus/config.yml
    rules:
      - value:
          image: prom/prometheus:latest
          command: --config.file=/etc/prometheus/prometheus.yml
          name: prom1
          mem_limit: 500m
          mem_reservation: 450m
          network: $network_name
          ports:
            9091: 9090
          volumes:
            $base_dir++/configs/prometheus/config.yml:
              bind: /etc/prometheus/prometheus.yml
              mode: ro
            prom1_vol:
              bind: /prometheus
              mode: rw

  awareness:
    containers: $awareness_q
    rules:
      - value:
          image: mbyzhang/awareness
          network: $network_name
          ports:
            6633: 6633
            8080: 8080
          environment:
            MININET_SERVER_URL: $mininet_server_url
      - target: [name, hostname]
        value: awareness1
        local_constants:
          - name: id
            type: auto_increment
            start: 1


  mininet:
    # currently only supports 0 or 1 mininet instances
    containers: $mininet_q
    rules:
      - value:
          name: mininet
          hostname: mininet
          image: mbyzhang/mininet
          privileged: True
          environment:
            MN_CONTROLLERS: $mininet_controllers
            MN_TOPO: $mininet_topo
            MN_SWITCH: $mininet_switch
          command: /mnscripts/mininet_rest rest-cli
          network: $network_name
          stdin_open: True
    hooks:
      postup-global:
        commands:
          - echo "Waiting for network topology discovery"
          - test $MININET_Q -ge 1 && sleep $TIME
        environment:
          - name: MININET_Q
            value: $mininet_q
          - name: TIME
            value: $network_discovery_time
  service_manager:
    constants:
      name_prefix: seed
      launcher: serviceManager
      key_services: sc1
    containers: $agent_sm_q
    rules: $^agent_common_rules
    hooks: $^agent_common_hooks

  function_provisioner:
    constants:
      name_prefix: prov
      launcher: functionProvisioner
      key_services: ""
    containers: $agent_fp_q
    rules: $^agent_common_rules
    hooks: $^agent_common_hooks

  digital_assets:
    constants:
      name_prefix: c
      launcher: digiAssetCustomArg
      key_services: ""
    containers: $agent_da_q
    rules: $^agent_common_rules
    hooks: $^agent_common_hooks
